#!/usr/bin/env node
// SKLand Wiki Data — JSON → XML → JSON round-trip semantic equivalence check

import { wikiJsonToXml, xmlToWikiJson, parseWikiJson, XmlWikiConversionError } from '@eihrteam/xml'
import { readFileSync } from 'fs'

function parseArgs() {
  const args = process.argv.slice(2)
  const opts = { input: null }

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--input') {
      opts.input = args[++i]
    }
  }

  return opts
}

function usage() {
  console.error(`Usage: node scripts/roundtrip-check.mjs --input <file.json>

Verifies that JSON → XML → JSON round-trip preserves DocumentModel semantic
equivalence. Compares structural fields (itemId, name, subType count,
chapterGroup count, description block count). Doesn't compare byte-level
JSON (IDs are regenerated by @eihrteam/xml).`)
  process.exit(1)
}

function checkRoundTrip(inputPath) {
  const rawJson = readFileSync(inputPath, 'utf8')

  // Step 1: parse input JSON
  const original = parseWikiJson(rawJson)

  // Step 2: JSON → XML
  const { text: xml } = wikiJsonToXml(rawJson)

  // Step 3: XML → JSON
  const { text: roundtrippedJson } = xmlToWikiJson(xml)

  // Step 4: parse round-tripped JSON
  const roundtripped = parseWikiJson(roundtrippedJson)

  // Step 5: compare structural fields (ignore regenerated IDs)
  const checks = {
    itemIdMatch: original.itemId === roundtripped.itemId,
    nameMatch: original.name === roundtripped.name,
    coverMatch: original.cover === roundtripped.cover,
    showInDetailMatch: original.showInDetail === roundtripped.showInDetail,
    subTypeCountMatch: original.subTypes.length === roundtripped.subTypes.length,
    descriptionWasNullMatch: original.descriptionWasNull === roundtripped.descriptionWasNull,
    descriptionBlockCountMatch: original.description.length === roundtripped.description.length,
    chapterGroupCountMatch: original.chapterGroups.length === roundtripped.chapterGroups.length,
  }

  // Step 6: check chapter group structure (deeper comparison)
  const chapterGroupChecks = []
  const maxGroups = Math.max(original.chapterGroups.length, roundtripped.chapterGroups.length)
  for (let i = 0; i < maxGroups; i++) {
    const orig = original.chapterGroups[i]
    const rt = roundtripped.chapterGroups[i]
    chapterGroupChecks.push({
      index: i,
      titleMatch: orig?.title === rt?.title,
      chapterCountMatch: orig?.chapters.length === rt?.chapters.length,
    })
  }

  const passed = Object.values(checks).every(Boolean) &&
    chapterGroupChecks.every(c => c.titleMatch && c.chapterCountMatch)

  const differences = []
  for (const [key, val] of Object.entries(checks)) {
    if (!val) differences.push(key)
  }
  for (const cg of chapterGroupChecks) {
    if (!cg.titleMatch) differences.push(`chapterGroup[${cg.index}].title`)
    if (!cg.chapterCountMatch) differences.push(`chapterGroup[${cg.index}].chapterCount`)
  }

  return {
    passed,
    checks,
    chapterGroupChecks,
    differences,
    summary: {
      originalChapterGroupCount: original.chapterGroups.length,
      roundtrippedChapterGroupCount: roundtripped.chapterGroups.length,
      originalDescriptionBlockCount: original.description.length,
      roundtrippedDescriptionBlockCount: roundtripped.description.length,
    },
  }
}

function main() {
  const opts = parseArgs()
  if (!opts.input) usage()

  try {
    const result = checkRoundTrip(opts.input)
    console.log(JSON.stringify(result, null, 2))
    if (!result.passed) {
      process.exitCode = 1
    }
  } catch (e) {
    if (e instanceof XmlWikiConversionError) {
      console.error(`Conversion error: ${e.message}`)
    } else {
      console.error(`Error: ${e.message}`)
    }
    process.exit(1)
  }
}

main()
